project:
  type: website
  resources:
    - "images/twitter-card.png"

website:
  page-navigation: true
  title: "Spatial predictive models with R"
  description: "Homepage for rstudio::conf(2022) workshop"
  site-url: ""
  repo-url: https://github.com/ambarja/website-quarto-template
  repo-actions: [edit, issue]
  open-graph: true
  twitter-card:
    creator: "@antony_barja"
    image: "/images/twitter-card.png"

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right: "&copy; Copyright 2022, Antony Barja"
    background: "#606060"

  navbar:
    background: "#606060"
    logo: "images/ggplot2.png"
    pinned: true
    align: center
    right:
      - icon: github
        href: https://github.com/rstudio-conf-2022/ggplot2-graphic-design
      - icon: twitter
        href: https://github.com/rstudio-conf-2022/ggplot2-graphic-design
      - icon: instagram
        href: https
      - icon: linkedin
        href: https
      - icon: facebook
        href: https        
    left:
     - href: index.qmd
       text: Home
     - href: installation.qmd
       text: Installation
     - text: Demos
       menu:
        - href: example01.qmd
          text: Example 01
        - href: example02.qmd
          text: Example 02
     - text: Resources
       menu:
        - href: https://geocompr.robinlovelace.net/
          text: Geocomputation with R
        - href: https://r-spatial.org/book/
          text: Spatial Data Science  
        - href: https://sdesabbata.github.io/r-for-geographic-data-science/
          text: R for Geographic Data Science

format:
  html:
    theme:
      light: [cosmo,theme.scss]
      dark: [cosmo, theme-dark.scss]
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: 'Roboto Slab'
    
editor: visual

