on:
  push:
    branches: main
  pull_request:
    branches: main
  workflow_dispatch:

name: Build Site

jobs:
  build-website:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Install Quarto CLI
        uses: quarto-dev/quarto-actions/install-quarto@v1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libprotobuf-dev
          sudo R -e 'install.packages(c("ggplot2", "readr", "tibble", "tidyr", "forcats", "stringr", "lubridate", "here", "systemfonts", "magick", "scales", "grid", "grDevices", "colorspace", "viridis", "RColorBrewer", "rcartocolor", "scico", "ggsci", "ggthemes", "nord", "MetBrewer", "ggrepel", "ggforce", "ggtext", "ggdist", "ggbeeswarm", "gghalves", "patchwork",  "palmerpenguins", "rnaturalearth", "sf", "rmapshaper", "devtools"))'
          sudo R -e 'remotes::install_github("wilkelab/cowplot")'
          sudo R -e 'remotes::install_github("clauswilke/colorblindr")'
      - name: Put pandoc in PATH
        run: |
          mkdir -p ~/.local/bin
          ln -s $(dirname $(readlink -f  $(which quarto)))"/pandoc" ~/.local/bin/pandoc
        shell: bash

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Render site
        # Add any command line argument needed
        run: |
          quarto render

      - name: Deploy 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
